/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/metaquast.py -R NC_003909.fna,NC_005707.fna -l abyss abyss_ctg.fasta

Version 2.2, build 19.07.2013 21:21


System information:
  OS: Linux-2.6.18-371.el5-x86_64-with-redhat-5.10-Tikanga
  Python version: 2.7.0
  CPUs number: 64

Started: 2014-03-24 13:28:46

Logging to /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/quast_results/results_2014_03_24_13_28_46/metaquast.log

References:
  NC_003909.fna ==> NC_003909
  NC_005707.fna ==> NC_005707
  All references combined in combined_reference.fasta

Contigs:
  abyss_ctg.fasta ==> abyss

Starting quast.py for the combined reference...
(logging to /usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/quast_results/results_2014_03_24_13_28_46/combined_quast_output/quast.log)

list index out of range
Traceback (most recent call last):
  File "./metaquast.py", line 511, in <module>
    return_code = main(sys.argv[1:])
  File "./metaquast.py", line 468, in main
    output_dirpath=os.path.join(output_dirpath, 'combined_quast_output'))
  File "./metaquast.py", line 159, in _start_quast_main
    return quast.main(args)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/quast.py", line 653, in main
    ref_fpath, contigs_fpaths, qconfig.prokaryote, os.path.join(output_dirpath, 'contigs_reports'))
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/contigs_analyzer.py", line 1270, in do
    for id, fname in enumerate(contigs_fpaths))
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/site_packages/joblib/parallel.py", line 483, in __call__
    self.dispatch(function, args, kwargs)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/site_packages/joblib/parallel.py", line 306, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/site_packages/joblib/parallel.py", line 134, in __init__
    self.results = func(*args, **kwargs)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/contigs_analyzer.py", line 1219, in plantakolya_process
    cyclic, i, contigs_fpath, nucmer_fname, myenv, output_dirpath, ref_fpath)
  File "/usit/invitro/data/galaxy/master/sabbai/galaxy-dist/tools/assembly_benchmark/quast/libs/contigs_analyzer.py", line 205, in plantakolya
    coords_file.write(header[-2])
IndexError: list index out of range
